language: node_js
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_938639410c7c_key -iv $encrypted_938639410c7c_iv
  -in rdss-api-gae.json.enc -out rdss-api-gae.json -d
deploy:
    provider: gae
    keyfile: ./rdss-api-gae.json
    project: rdss-api
