language: python
python:
- "2.7"
# install dependency
# install: "pip install -r requirements.txt"
install: "echo 'nothing to install for now.'"
# run tests
# script: nosetests
script: "echo 'nothing to test for now.'"
before_install:
- openssl aes-256-cbc -K $encrypted_938639410c7c_key -iv $encrypted_938639410c7c_iv
  -in rdss-api-gae.json.enc -out rdss-api-gae.json -d

# https://code.google.com/p/google-cloud-sdk/issues/detail?id=727
#before_deploy:
#- gcloud config set app/use_gsutil true

deploy:
    provider: gae
    keyfile: ./rdss-api-gae.json
    project: rdss-api
