runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /stylesheets
  static_dir: public/stylesheets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

